version: '3'
services:
  front:
    image: node:latest
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 8080:8080
    command: "npm run serve"
  proxy-reverse:
    depends_on:
      - front
    image: nginx:latest
      volumes:
        - .:/usr/share/nginx/html/
        - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./.nginx/certs:/etc/ssl/certs/nginx/
    ports:
      - 80:80
      - 443:443

